### ISSUE TITLE
Meaning of output_tensor[0]

### ISSUE THREAD

**Issue by erehzio** [Prem95/realtime-face-liveness-detector#11]
Hello, congrats for great work.

I figure out the output_data has 2 positions.

np.round(output_data[:, 1][0], 3) .

In your example, you used the position 1 to calculate the predict score. What's the meaning of the position 0, in this model? Could it be the confidence about the prediction?

**Comment by Prem95** [comment]
Hi there, yes you are right. It simply means the spoofing confidence score.
