### ISSUE TITLE
Runtime error found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by 123artorux** [Prem95/realtime-face-liveness-detector#12]
I got this error when I try to run the main.py on macOS. Does the project require NVIDIA to run?

**Comment by Prem95** [comment]
Hi there, it is possible that your GPU does not support CUDA. Yes, this project requires NVIDIA to run

**Comment by 123artorux** [comment]
Ah i see, that seems to be the cause. I am currently using virtualbox to run the project on macOS
