### ISSUE TITLE
Using RBG or BGR?

### ISSUE THREAD

**Issue by SamanKhamesian** [Prem95/realtime-face-liveness-detector#14]
https://github.com/Prem95/realtime-face-liveness-detector/blob/89a1109a18e6be227f02233ed6f36e15501fe106/main.py#L61

Hi,
The return value of cv2.VideoCapture(0) is based on BGR format by default. You should not convert it in line 61.

**Comment by Prem95** [comment]
Hi, the reason for converting is related to how the Face Detector crops the incoming face and what data the face detector model was trained on.
