### ISSUE TITLE
Can this run on CPU-only computer?

### ISSUE THREAD

**Issue by Dnlee17** [Prem95/realtime-face-liveness-detector#19]
Hi @Prem95 
Can this run on CPU-only computer?
If so, how can I modify your code 
thanks!

**Comment by Prem95** [comment]
Hi there, the models are trained on a GPU, but I believe TF has functions to force to load the model on a CPU memory instead of a GPU. You can take a look at this [StackOverflow](https://stackoverflow.com/questions/40690598/can-keras-with-tensorflow-backend-be-forced-to-use-cpu-or-gpu-at-will)
