### ISSUE TITLE
Missing utility.video_utils

### ISSUE THREAD

**Issue by eduardocalazansjr** [Prem95/realtime-face-liveness-detector#21]
**Describe the bug**
I'm trying to run the project but got an missing module error

```
➜  face-liveness-detector (main) ✔ python3 main.py

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from utility.video_utils import VideoUtils
ModuleNotFoundError: No module named 'utility'
```

**To Reproduce**
1. Clone project
2. Build face_det folder
3. Run python3 main.py
4. Got ModuleNotFoundError

**Expected behavior**
The project runs fine

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by Prem95** [comment]
Contact premstroke95@gmail.com to request the sample model file and utility folder. The sample model file has an accuracy of 75% and can only be used for testing purposes.

**Comment by mrzaizai2k** [comment]
The folder is sold for USD 80
