### ISSUE TITLE
Could you please release the code of model structure and how to train 

### ISSUE THREAD

**Issue by Iron-iii** [Prem95/realtime-face-liveness-detector#24]

**Comment by Iron-iii** [comment]
Your pretrtained model performances well in test, there is TDDFA in code,  pretrained model h5 file is a binary classification model, did the model trained with  depthmap auxiliary classification

**Comment by Iron-iii** [comment]
Looking forward to your reply

**Comment by Prem95** [comment]
The model is not trained with depthmap data, but it is not from TDDFA.
TDDFA is used for face detection

**Comment by Iron-iii** [comment]
> 

if model is trained with binary classification, reault is amazing

**Comment by Prem95** [comment]
thanks!
